/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

import { BaseResource, CloudError } from "ms-rest-azure-js";
import * as msRest from "ms-rest-js";

export { BaseResource, CloudError };


/**
 * @interface
 * An interface representing GetQueueResponse.
 * The response from a GetQueue operation
 *
 */
export interface GetQueueResponse {
  /**
   * @member {string} [id] The ID Of the Queue
   */
  id?: string;
}


/**
 * Contains response data for the get operation.
 */
export type QueueGetResponse = GetQueueResponse & {
  /**
   * The underlying HTTP response.
   */
  _response: msRest.HttpResponse & {
      /**
       * The response body as text (string format)
       */
      bodyAsText: string;
      /**
       * The response body as parsed JSON or XML
       */
      parsedBody: GetQueueResponse;
    };
};
