/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

import { CloudErrorMapper, BaseResourceMapper } from "ms-rest-azure-js";
import * as msRest from "ms-rest-js";

export const CloudError = CloudErrorMapper;
export const BaseResource = BaseResourceMapper;

export const GetQueueResponse: msRest.CompositeMapper = {
  xmlName: "entry",
  serializedName: "GetQueueResponse",
  type: {
    name: "Composite",
    className: "GetQueueResponse",
    modelProperties: {
      id: {
        xmlName: "id",
        serializedName: "id",
        type: {
          name: "String"
        }
      }
    }
  }
};
