/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

import { CloudErrorMapper, BaseResourceMapper } from "ms-rest-azure-js";
import * as msRest from "ms-rest-js";

export const CloudError = CloudErrorMapper;
export const BaseResource = BaseResourceMapper;

export const GetQueueResponseAuthor: msRest.CompositeMapper = {
  serializedName: "GetQueueResponse_author",
  type: {
    name: "Composite",
    className: "GetQueueResponseAuthor",
    modelProperties: {
      name: {
        xmlName: "name",
        serializedName: "name",
        type: {
          name: "String"
        }
      }
    }
  }
};

export const GetQueueResponseLink: msRest.CompositeMapper = {
  serializedName: "GetQueueResponse_link",
  type: {
    name: "Composite",
    className: "GetQueueResponseLink",
    modelProperties: {
      rel: {
        xmlIsAttribute: true,
        xmlName: "rel",
        serializedName: "rel",
        type: {
          name: "String"
        }
      },
      href: {
        xmlIsAttribute: true,
        xmlName: "href",
        serializedName: "href",
        type: {
          name: "String"
        }
      }
    }
  }
};

export const GetQueueResponseContentQueueDescriptionCountDetails: msRest.CompositeMapper = {
  serializedName: "GetQueueResponse_content_QueueDescription_CountDetails",
  type: {
    name: "Composite",
    className: "GetQueueResponseContentQueueDescriptionCountDetails",
    modelProperties: {
      activeMessageCount: {
        xmlName: "d2p1:ActiveMessageCount",
        serializedName: "d2p1:ActiveMessageCount",
        type: {
          name: "Number"
        }
      },
      deadLetterMessageCount: {
        xmlName: "d2p1:DeadLetterMessageCount",
        serializedName: "d2p1:DeadLetterMessageCount",
        type: {
          name: "Number"
        }
      },
      scheduledMessageCount: {
        xmlName: "d2p1:ScheduledMessageCount",
        serializedName: "d2p1:ScheduledMessageCount",
        type: {
          name: "Number"
        }
      },
      transferMessageCount: {
        xmlName: "d2p1:TransferMessageCount",
        serializedName: "d2p1:TransferMessageCount",
        type: {
          name: "Number"
        }
      },
      transferDeadLetterMessageCount: {
        xmlName: "d2p1:TransferDeadLetterMessageCount",
        serializedName: "d2p1:TransferDeadLetterMessageCount",
        type: {
          name: "Number"
        }
      }
    }
  }
};

export const GetQueueResponseContentQueueDescription: msRest.CompositeMapper = {
  serializedName: "GetQueueResponse_content_QueueDescription",
  type: {
    name: "Composite",
    className: "GetQueueResponseContentQueueDescription",
    modelProperties: {
      lockDuration: {
        xmlName: "LockDuration",
        serializedName: "LockDuration",
        type: {
          name: "String"
        }
      },
      maxSizeInMegabytes: {
        xmlName: "MaxSizeInMegabytes",
        serializedName: "MaxSizeInMegabytes",
        type: {
          name: "Number"
        }
      },
      requiresDuplicateDetection: {
        xmlName: "RequiresDuplicateDetection",
        serializedName: "RequiresDuplicateDetection",
        type: {
          name: "Boolean"
        }
      },
      requiresSession: {
        xmlName: "RequiresSession",
        serializedName: "RequiresSession",
        type: {
          name: "Boolean"
        }
      },
      defaultMessageTimeToLive: {
        xmlName: "DefaultMessageTimeToLive",
        serializedName: "DefaultMessageTimeToLive",
        type: {
          name: "String"
        }
      },
      deadLetteringOnMessageExpiration: {
        xmlName: "DeadLetteringOnMessageExpiration",
        serializedName: "DeadLetteringOnMessageExpiration",
        type: {
          name: "Boolean"
        }
      },
      duplicateDetectionHistoryTimeWindow: {
        xmlName: "DuplicateDetectionHistoryTimeWindow",
        serializedName: "DuplicateDetectionHistoryTimeWindow",
        type: {
          name: "String"
        }
      },
      maxDeliveryCount: {
        xmlName: "MaxDeliveryCount",
        serializedName: "MaxDeliveryCount",
        type: {
          name: "Number"
        }
      },
      enableBatchedOperations: {
        xmlName: "EnableBatchedOperations",
        serializedName: "EnableBatchedOperations",
        type: {
          name: "Boolean"
        }
      },
      sizeInBytes: {
        xmlName: "SizeInBytes",
        serializedName: "SizeInBytes",
        type: {
          name: "Number"
        }
      },
      messageCount: {
        xmlName: "MessageCount",
        serializedName: "MessageCount",
        type: {
          name: "Number"
        }
      },
      isAnonymousAccessible: {
        xmlName: "IsAnonymousAccessible",
        serializedName: "IsAnonymousAccessible",
        type: {
          name: "Boolean"
        }
      },
      status: {
        xmlName: "Status",
        serializedName: "Status",
        type: {
          name: "String"
        }
      },
      createdAt: {
        xmlName: "CreatedAt",
        serializedName: "CreatedAt",
        type: {
          name: "String"
        }
      },
      updatedAt: {
        xmlName: "UpdatedAt",
        serializedName: "UpdatedAt",
        type: {
          name: "String"
        }
      },
      accessedAt: {
        xmlName: "AccessedAt",
        serializedName: "AccessedAt",
        type: {
          name: "String"
        }
      },
      supportOrdering: {
        xmlName: "SupportOrdering",
        serializedName: "SupportOrdering",
        type: {
          name: "Boolean"
        }
      },
      countDetails: {
        xmlName: "CountDetails",
        serializedName: "CountDetails",
        type: {
          name: "Composite",
          className: "GetQueueResponseContentQueueDescriptionCountDetails"
        }
      },
      autoDeleteOnIdle: {
        xmlName: "AutoDeleteOnIdle",
        serializedName: "AutoDeleteOnIdle",
        type: {
          name: "String"
        }
      },
      enablePartitioning: {
        xmlName: "EnablePartitioning",
        serializedName: "EnablePartitioning",
        type: {
          name: "Boolean"
        }
      },
      entityAvailabilityStatus: {
        xmlName: "EntityAvailabilityStatus",
        serializedName: "EntityAvailabilityStatus",
        type: {
          name: "String"
        }
      },
      enableExpress: {
        xmlName: "EnableExpress",
        serializedName: "EnableExpress",
        type: {
          name: "Boolean"
        }
      }
    }
  }
};

export const GetQueueResponseContent: msRest.CompositeMapper = {
  serializedName: "GetQueueResponse_content",
  type: {
    name: "Composite",
    className: "GetQueueResponseContent",
    modelProperties: {
      type: {
        xmlIsAttribute: true,
        xmlName: "type",
        serializedName: "type",
        type: {
          name: "String"
        }
      },
      queueDescription: {
        xmlName: "QueueDescription",
        serializedName: "QueueDescription",
        type: {
          name: "Composite",
          className: "GetQueueResponseContentQueueDescription"
        }
      }
    }
  }
};

export const GetQueueResponse: msRest.CompositeMapper = {
  xmlName: "entry",
  serializedName: "GetQueueResponse",
  type: {
    name: "Composite",
    className: "GetQueueResponse",
    modelProperties: {
      id: {
        xmlName: "id",
        required: true,
        serializedName: "id",
        type: {
          name: "String"
        }
      },
      title: {
        xmlName: "title",
        serializedName: "title",
        type: {
          name: "String"
        }
      },
      published: {
        xmlName: "published",
        required: true,
        serializedName: "published",
        type: {
          name: "String"
        }
      },
      updated: {
        xmlName: "updated",
        serializedName: "updated",
        type: {
          name: "String"
        }
      },
      author: {
        xmlName: "author",
        required: true,
        serializedName: "author",
        type: {
          name: "Composite",
          className: "GetQueueResponseAuthor"
        }
      },
      link: {
        xmlName: "link",
        required: true,
        serializedName: "link",
        type: {
          name: "Composite",
          className: "GetQueueResponseLink"
        }
      },
      content: {
        xmlName: "content",
        required: true,
        serializedName: "content",
        type: {
          name: "Composite",
          className: "GetQueueResponseContent"
        }
      }
    }
  }
};

export const CreateQueueBodyContentQueueDescription: msRest.CompositeMapper = {
  serializedName: "CreateQueueBody_content_QueueDescription",
  type: {
    name: "Composite",
    className: "CreateQueueBodyContentQueueDescription",
    modelProperties: {
      lockDuration: {
        xmlName: "LockDuration",
        serializedName: "LockDuration",
        defaultValue: 'PT1M',
        type: {
          name: "String"
        }
      },
      maxSizeInMegabytes: {
        xmlName: "MaxSizeInMegabytes",
        serializedName: "MaxSizeInMegabytes",
        defaultValue: 1024,
        type: {
          name: "Number"
        }
      },
      requiresDuplicateDetection: {
        xmlName: "RequiresDuplicateDetection",
        serializedName: "RequiresDuplicateDetection",
        defaultValue: false,
        type: {
          name: "Boolean"
        }
      },
      requiresSession: {
        xmlName: "RequiresSession",
        serializedName: "RequiresSession",
        defaultValue: false,
        type: {
          name: "Boolean"
        }
      },
      deadLetteringOnMessageExpiration: {
        xmlName: "DeadLetteringOnMessageExpiration",
        serializedName: "DeadLetteringOnMessageExpiration",
        defaultValue: false,
        type: {
          name: "Boolean"
        }
      },
      maxDeliveryCount: {
        xmlName: "MaxDeliveryCount",
        serializedName: "MaxDeliveryCount",
        defaultValue: 10,
        type: {
          name: "Number"
        }
      },
      enableBatchedOperations: {
        xmlName: "EnableBatchedOperations",
        serializedName: "EnableBatchedOperations",
        defaultValue: true,
        type: {
          name: "Boolean"
        }
      },
      status: {
        xmlName: "Status",
        serializedName: "Status",
        defaultValue: 'Active',
        type: {
          name: "String"
        }
      },
      enablePartitioning: {
        xmlName: "EnablePartitioning",
        serializedName: "EnablePartitioning",
        defaultValue: false,
        type: {
          name: "Boolean"
        }
      }
    }
  }
};

export const CreateQueueBodyContent: msRest.CompositeMapper = {
  serializedName: "CreateQueueBody_content",
  type: {
    name: "Composite",
    className: "CreateQueueBodyContent",
    modelProperties: {
      type: {
        xmlIsAttribute: true,
        xmlName: "type",
        serializedName: "type",
        type: {
          name: "String"
        }
      },
      queueDescription: {
        xmlName: "QueueDescription",
        serializedName: "QueueDescription",
        type: {
          name: "Composite",
          className: "CreateQueueBodyContentQueueDescription"
        }
      }
    }
  }
};

export const CreateQueueBody: msRest.CompositeMapper = {
  xmlName: "entry",
  serializedName: "CreateQueueBody",
  type: {
    name: "Composite",
    className: "CreateQueueBody",
    modelProperties: {
      content: {
        xmlName: "content",
        serializedName: "content",
        type: {
          name: "Composite",
          className: "CreateQueueBodyContent"
        }
      }
    }
  }
};
